app:
    resource: '@AppBundle/Controller/'
    type: annotation

#app_patient:
 #   resource: '@AppBundle/Test/Controller/'
   # type: annotation
   # prefix: /patient


admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
    path: /register/
    defaults: {_controller: 'AppBundle:User\Registration:register'}

homepage:
    path: /
    defaults:  { _controller: 'FOSUserBundle:Security:login' }

user_page:
    path: /personal/
    defaults: {_controller: 'AppBundle:UserStart:index'}

ticket_list:
    path: /ticket-list/
    defaults: {_controller: 'AppBundle:Ticket:activeTickets'}

specialty_list:
    path: /specialty-list/
    defaults: {_controller: 'AppBundle:Ticket:specialty'}

doctor_list:
    path: /doctor-list/{specialty}
    defaults: {_controller: 'AppBundle:Ticket:doctor'}
    requirements:
        page: '\d+'

date_list:
    path: /date-list/{doctor}/{date}
    defaults: {_controller: 'AppBundle:Ticket:date', date: null}
    requirements:
        page: '\d+'

time_list:
    path: /ticket-confirm/
    defaults: {_controller: 'AppBundle:Ticket:confirmTicket'}



